#pragma once
namespace JSLib {
enum class StatementType{
    PROGRAM, IF_STATEMENT, FOR_STATEMENT, WHILE_STATEMENT, SWITCH_CASE_STATEMENT,IMMEDIATE_STATEMENT,BINARY_OP_STATEMENT,VARIABLE_STATEMENT, UNARY_OP_STATEMENT, ASSIGNMENT_STATEMENT,
    FUNCTION_STATEMENT, CLASS_STATEMENT, VARIABLE_DECLARATION_STATEMENT, BOOL_STATEMENT, ANY_OF_STATEMENT_TYPES, INVALID_STATEMENT
};
    enum class BinaryOpSubType {
        ADD, MUL, SUB, DIV, MOD, POW, BITWISE_OR, BITWISE_XOR, BITWISE_AND, SHIFT_LEFT, SHIFT_RIGHT, LOGICAL_XOR,
        LOGICAL_OR, LOGICAL_AND, IS_EQUAL, IS_NOT_EQUAL, IS_ABS_EQUAL, IS_NOT_ABS_EQUAL, GREATER_THAN, LESS_THAN,
        GREATER_OR_EQUAL, LESS_OR_EQUAL
    };

    enum class UnaryOpSubType {
        INC, DEC, BITWISE_NOT, LOGICAL_NOT,
    };
}
