#pragma once
namespace JSLib {
enum class StatementType{
    PROGRAM, IF_STATEMENT, FOR_STATEMENT, WHILE_STATEMENT, SWITCH_CASE_STATEMENT,BINARY_OP_STATEMENT, 
    FUNCTION_STATEMENT, CLASS_STATEMENT, VARIABLE_DECLARATION, BOOL_STATEMENT, ANY_OF_STATEMENT_TYPES, INVALID_STATEMENT
};
}
