
#pragma once
namespace JSLib {
    enum class StatementType{
        PROGRAM, IF_STATEMENT, FOR_STATEMENT, WHILE_STATEMENT, SWITCH_CASE_STATEMENT,IMMEDIATE_STATEMENT,BINARY_OP_STATEMENT,VARIABLE_STATEMENT, UNARY_OP_STATEMENT, ASSIGNMENT_STATEMENT,
        FUNCTION_STATEMENT, CLASS_STATEMENT, VARIABLE_DECLARATION_STATEMENT, BOOL_STATEMENT, ANY_OF_STATEMENT_TYPES, INVALID_STATEMENT
    };
    enum class BinaryOpSubType {
        POW= 9,
        MUL=8,DIV=8,MOD=8,
        ADD=7,SUB=7,
        SHIFT_LEFT=6,SHIFT_RIGHT=6,
        IN= 5,INSTANCEOF = 5,GREATER_THAN = 5,LESS_THAN =5 ,GREATER_OR_EQUAL =5 ,LESS_OR_EQUAL=5,
        IS_EQUAL=4, IS_NOT_EQUAL=4, IS_STRICTLY_EQUAL=4, IS_NOT_STRICTLY_EQUAL=4,
        BITWISE_OR = 3, BITWISE_XOR = 3, BITWISE_AND = 3,
        LOGICAL_OR = 2, LOGICAL_AND = 2
    };

    enum class UnaryOpSubType {
        INC, DEC, BITWISE_NOT, LOGICAL_NOT,
    };
}
